// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZXAk-kF4_Gq3xcKEc0YhYZEf6bNoWiuM',
    appId: '1:21942538465:web:52d747ab522deaeb3167a0',
    messagingSenderId: '21942538465',
    projectId: 'careershield-1f184',
    authDomain: 'careershield-1f184.firebaseapp.com',
    storageBucket: 'careershield-1f184.firebasestorage.app',
    measurementId: 'G-6RF09E6YE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCskjxOOHGMVEeJKCGWBnOE2d5qWjiMkwA',
    appId: '1:21942538465:android:d3195964595f7bbf3167a0',
    messagingSenderId: '21942538465',
    projectId: 'careershield-1f184',
    storageBucket: 'careershield-1f184.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbPMEKcYJFk2GpsHu1F3MqYbNYv53ylxs',
    appId: '1:21942538465:ios:4cba60335fbcd9123167a0',
    messagingSenderId: '21942538465',
    projectId: 'careershield-1f184',
    storageBucket: 'careershield-1f184.firebasestorage.app',
    iosBundleId: 'com.example.careershieldAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbPMEKcYJFk2GpsHu1F3MqYbNYv53ylxs',
    appId: '1:21942538465:ios:4cba60335fbcd9123167a0',
    messagingSenderId: '21942538465',
    projectId: 'careershield-1f184',
    storageBucket: 'careershield-1f184.firebasestorage.app',
    iosBundleId: 'com.example.careershieldAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZXAk-kF4_Gq3xcKEc0YhYZEf6bNoWiuM',
    appId: '1:21942538465:web:0029528c87cebc753167a0',
    messagingSenderId: '21942538465',
    projectId: 'careershield-1f184',
    authDomain: 'careershield-1f184.firebaseapp.com',
    storageBucket: 'careershield-1f184.firebasestorage.app',
    measurementId: 'G-RBPR1157CS',
  );
}
